version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node

    steps:
      - checkout

      - restore_cache:
          key: baccanoio-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: baccanoio-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - baccanoio-npm-v2-{{ checksum "package-lock.json" }}
            - baccanoio-npm-v2-

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          key: baccanoio-npm-v2-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules

      - run:
          name: Build Middleman site
          command: bin/build

      - run:
          name: Run HTMLProofer
          command: bin/test
